"""create models: releases, sessions, sessions_moods, discogs_release_cache

Revision ID: 1a8551e314b6
Revises: eed6974773b8
Create Date: 2026-04-10 16:29:03.796685

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1a8551e314b6"
down_revision: str | Sequence[str] | None = "eed6974773b8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "discogs_release_cache",
        sa.Column("discogs_release_id", sa.BigInteger(), nullable=False),
        sa.Column("raw_discogs_json", sa.JSON(), nullable=False),
        sa.Column("cached_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("last_accessed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("discogs_release_id"),
    )
    op.create_table(
        "session_moods",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("is_custom", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("releases", sa.Column("discogs_release_id", sa.BigInteger(), nullable=False))
    op.add_column("releases", sa.Column("year", sa.Integer(), nullable=True))
    op.add_column("releases", sa.Column("label", sa.String(), nullable=True))
    op.add_column("releases", sa.Column("catalog_number", sa.String(), nullable=True))
    op.add_column("releases", sa.Column("barcode", sa.String(), nullable=True))
    op.add_column("releases", sa.Column("genres", sa.ARRAY(sa.String()), nullable=True))
    op.add_column("releases", sa.Column("styles", sa.ARRAY(sa.String()), nullable=True))
    op.add_column("releases", sa.Column("cover_image_url", sa.String(), nullable=True))
    op.add_column(
        "releases", sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False)
    )
    op.add_column(
        "releases", sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False)
    )
    op.alter_column("releases", "id", existing_type=sa.INTEGER(), type_=sa.String(), existing_nullable=False)
    op.drop_index(op.f("ix_releases_id"), table_name="releases")
    op.add_column("sessions", sa.Column("release_id", sa.String(), nullable=False))
    op.add_column("sessions", sa.Column("rating", sa.Integer(), nullable=True))
    op.add_column("sessions", sa.Column("mood", sa.String(), nullable=True))
    op.add_column("sessions", sa.Column("notes", sa.String(), nullable=True))
    op.add_column("sessions", sa.Column("played_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("sessions", sa.Column("vinyl_side", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sessions", "vinyl_side")
    op.drop_column("sessions", "played_at")
    op.drop_column("sessions", "notes")
    op.drop_column("sessions", "mood")
    op.drop_column("sessions", "rating")
    op.drop_column("sessions", "release_id")
    op.create_index(op.f("ix_releases_id"), "releases", ["id"], unique=False)
    op.alter_column("releases", "id", existing_type=sa.String(), type_=sa.INTEGER(), existing_nullable=False)
    op.drop_column("releases", "updated_at")
    op.drop_column("releases", "created_at")
    op.drop_column("releases", "cover_image_url")
    op.drop_column("releases", "styles")
    op.drop_column("releases", "genres")
    op.drop_column("releases", "barcode")
    op.drop_column("releases", "catalog_number")
    op.drop_column("releases", "label")
    op.drop_column("releases", "year")
    op.drop_column("releases", "discogs_release_id")
    op.drop_table("session_moods")
    op.drop_table("discogs_release_cache")
    # ### end Alembic commands ###
