"""latest DB revision

Revision ID: a5427b530a12
Revises: 1a8551e314b6
Create Date: 2026-04-19 16:43:24.305430

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a5427b530a12"
down_revision: str | Sequence[str] | None = "1a8551e314b6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "discogs_release_cache",
        "raw_discogs_json",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.create_index(
        "idx_discogs_release_cache_last_accessed_at", "discogs_release_cache", ["last_accessed_at"], unique=False
    )
    op.create_index("idx_releases_artist", "releases", ["artist"], unique=False)
    op.create_index("idx_releases_genres", "releases", ["genres"], unique=False, postgresql_using="gin")
    op.create_index("idx_releases_styles", "releases", ["styles"], unique=False, postgresql_using="gin")
    op.create_index("idx_releases_title", "releases", ["title"], unique=False)
    op.create_unique_constraint(None, "releases", ["discogs_release_id"])
    op.create_unique_constraint(None, "session_moods", ["name"])
    op.create_index("idx_sessions_played_at", "sessions", ["played_at"], unique=False)
    op.create_index("idx_sessions_release_id", "sessions", ["release_id"], unique=False)
    op.create_foreign_key(None, "sessions", "releases", ["release_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "sessions", type_="foreignkey")
    op.drop_index("idx_sessions_release_id", table_name="sessions")
    op.drop_index("idx_sessions_played_at", table_name="sessions")
    op.drop_constraint(None, "session_moods", type_="unique")
    op.drop_constraint(None, "releases", type_="unique")
    op.drop_index("idx_releases_title", table_name="releases")
    op.drop_index("idx_releases_styles", table_name="releases", postgresql_using="gin")
    op.drop_index("idx_releases_genres", table_name="releases", postgresql_using="gin")
    op.drop_index("idx_releases_artist", table_name="releases")
    op.drop_index("idx_discogs_release_cache_last_accessed_at", table_name="discogs_release_cache")
    op.alter_column(
        "discogs_release_cache",
        "raw_discogs_json",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
